### ISSUE TITLE
Yank persistence across Neovim sessions.

### ISSUE THREAD

**Issue by rmagatti** [AckslD/nvim-neoclip.lua#16]
Hey @AckslD first off thanks for the great plugin, looks like I found my `coc-yank` alternative!

I noticed that yanks are not kept between Neovim sessions.
i.e if I yank something, save my current neovim session, close neovim, open neovim, reload the session and start up neoclip, the things I had previously yanked before closing are not visible in the list anymore.

Non-empty registers get saved in Neovim's ShaDa file by default, I think a very cool optional feature to have would be populating the contents of the list through what gets read from the file (or just by reading the registers sometime after startup?).

Let me know if this sounds feasible or not, we can discuss further as to how this would work if you're interested.

**Comment by AckslD** [comment]
Hi @rmagatti! Thanks for the suggestion :)

I think being able to save the history (optionally) between sessions would be great. I think we should actually save the whole session stored in the neoclip storage and not only read from what's in the ShaDa file.

@fdschmidt93 suggested some time ago that for example https://github.com/tami5/sql.nvim could be used for this. What do you think?

I'm currently on holidays and won't have much time to work on this new feature. If you feel like starting the implementation, feel free to do so. :) Otherwise I'll look into it later.

**Comment by rmagatti** [comment]
Interesting, I was thinking something as simple as reading from the registers and populating neoclip's storage with data from it at load time would be pretty acceptable as a starting point at least.

Actually using a separate persistence mechanism sounds cool but also a bit like overkill? At least considering that the contents one would want are likely already in the registers after Neovim's loading of the ShaDa file's contents.

I can probably take a crack at this come weekend time if I find myself with some time on my hands. I'll update my findings here if I get to it, thanks for the discussion so far! 😃

**Comment by AckslD** [comment]
@rmagatti Just FYI I started trying out how this might work in #20 :)

**Comment by AckslD** [comment]
Hi @rmagatti @kdurant I now finished implementing the persistent history using `sqlite.lua` in #20. Feel free to try it out and let me know if you have any issues.

**Comment by rmagatti** [comment]
Will do, thanks for working on this!

**Comment by AckslD** [comment]
Just merged #20 so closing this, let me know if you have any issues
