### ISSUE TITLE
how set cursore at end of paste

### ISSUE THREAD

**Issue by ayoubelmhamdi** [AckslD/nvim-neoclip.lua#21]
```lua
require('neoclip').setup({
  keys = {
        i = {
          paste = '<c-p>',
        },
})
```
when using `CTRL` `p` cursor  move to the start of `TextPasted`, can set the cursor to go to end of `TextPasted`   
something like `gvo`

**Comment by AckslD** [comment]
Hi @ayoubelmhamdi! Do you mean in the same way as `gp`?

**Comment by ayoubelmhamdi** [comment]
you are using  `gp`, so: I want `gP`

**Comment by AckslD** [comment]
@ayoubelmhamdi Actually `p` is currently used (and `P` which is by default bound to `<c-k>` in insert mode and `P` in normal) as you can see [here](https://github.com/AckslD/nvim-neoclip.lua/blob/920928e5aed5b1eb9c220ff3ce281d94da0fc1af/lua/telescope/_extensions/neoclip.lua#L101). Let me know if that clarifies things for you since I'm still a bit unsure what you're exactly asking for :)
